### ISSUE TITLE
Arduino serial com issue

### ISSUE THREAD

**Issue by tmopencell** [brianchowlab/OSP#2]
After typing `sudo python GUI.pys the code begins to execute but hangs when trying to initialise serial coms with the arduino: 

Actual output error:
```
[[1033.         1526.66666667]
 [1097.         1526.66666667]
 [1161.         1526.66666667]
 [1225.         1526.66666667]
 [1289.         1526.66666667]
 [1353.         1526.66666667]
 [1417.         1526.66666667]
 [1481.         1526.66666667]
 [1545.         1526.66666667]
 [1609.         1526.66666667]
 [1673.         1526.66666667]
 [1737.         1526.66666667]
 [1033.         1456.66666667]
 [1097.         1456.66666667]
 [1161.         1456.66666667]
 [1225.         1456.66666667]
 [1289.         1456.66666667]
 [1353.         1456.66666667]
 [1417.         1456.66666667]
 [1481.         1456.66666667]
 [1545.         1456.66666667]
 [1609.         1456.66666667]
 [1673.         1456.66666667]
 [1737.         1456.66666667]
 [1033.         1386.66666667]
 [1097.         1386.66666667]
 [1161.         1386.66666667]
 [1225.         1386.66666667]
 [1289.         1386.66666667]
 [1353.         1386.66666667]
 [1417.         1386.66666667]
 [1481.         1386.66666667]
 [1545.         1386.66666667]
 [1609.         1386.66666667]
 [1673.         1386.66666667]
 [1737.         1386.66666667]
 [1033.         1316.66666667]
 [1097.         1316.66666667]
 [1161.         1316.66666667]
 [1225.         1316.66666667]
 [1289.         1316.66666667]
 [1353.         1316.66666667]
 [1417.         1316.66666667]
 [1481.         1316.66666667]
 [1545.         1316.66666667]
 [1609.         1316.66666667]
 [1673.         1316.66666667]
 [1737.         1316.66666667]
 [1033.         1246.66666667]
 [1097.         1246.66666667]
 [1161.         1246.66666667]
 [1225.         1246.66666667]
 [1289.         1246.66666667]
 [1353.         1246.66666667]
 [1417.         1246.66666667]
 [1481.         1246.66666667]
 [1545.         1246.66666667]
 [1609.         1246.66666667]
 [1673.         1246.66666667]
 [1737.         1246.66666667]
 [1033.         1176.66666667]
 [1097.         1176.66666667]
 [1161.         1176.66666667]
 [1225.         1176.66666667]
 [1289.         1176.66666667]
 [1353.         1176.66666667]
 [1417.         1176.66666667]
 [1481.         1176.66666667]
 [1545.         1176.66666667]
 [1609.         1176.66666667]
 [1673.         1176.66666667]
 [1737.         1176.66666667]
 [1033.         1106.66666667]
 [1097.         1106.66666667]
 [1161.         1106.66666667]
 [1225.         1106.66666667]
 [1289.         1106.66666667]
 [1353.         1106.66666667]
 [1417.         1106.66666667]
 [1481.         1106.66666667]
 [1545.         1106.66666667]
 [1609.         1106.66666667]
 [1673.         1106.66666667]
 [1737.         1106.66666667]
 [1033.         1036.66666667]
 [1097.         1036.66666667]
 [1161.         1036.66666667]
 [1225.         1036.66666667]
 [1289.         1036.66666667]
 [1353.         1036.66666667]
 [1417.         1036.66666667]
 [1481.         1036.66666667]
 [1545.         1036.66666667]
 [1609.         1036.66666667]
 [1673.         1036.66666667]
 [1737.         1036.66666667]]
Machine Initialized
Traceback (most recent call last):
  File "GUI.py", line 1169, in <module>
    main()
  File "GUI.py", line 1164, in main
    ex = GUI(0)
  File "GUI.py", line 54, in __init__
    self.initialize_machine()
  File "/home/pi/OSP/Software/Python Files/System.py", line 400, in initialize_machine
    self.machine = Machine(self.savedSettings)
  File "/home/pi/OSP/Software/Python Files/Machine.py", line 10, in __init__
    self.initialize_arduino()
  File "/home/pi/OSP/Software/Python Files/Machine.py", line 18, in initialize_arduino
    self.arduino = Arduino()
  File "/home/pi/OSP/Software/Python Files/Arduino.py", line 34, in __init__
    raise IOError("No ser found")
IOError: No ser found
```

You can see that it is hanging on an error thrown in **Arduino.py**. Looking in there we see that the code is designed to recognise the operating system we are running and then look for a serial/com port with ACM in the name:
```
        elif platform.system() == 'Linux':
            ser_ports = [
                p.device
                for p in serial.tools.list_ports.comports()
                if 'ACM' in p.description
            ]
```

We can check that this is not the issue and after typing `python` and `import platform`, we can then type `platform.system()` and we see output is Linux, happy days. However, when we then type `import serial.tools.list_ports` and execute `serial.tools.list_ports.comports()` **we start to see the possible issue**.. Output: 

```
[<serial.tools.list_ports_linux.SysFS object at 0x76913610>, <serial.tools.list_ports_linux.SysFS object at 0x769136b0>]
```
 No trace of the ACM (like what we see in the output described in [this issue report](https://github.com/pyserial/pyserial/issues/54).... **Expected output** is something like this: 

```
/dev/ttyACM0
    desc: ttyACM0
    hwid: USB VID:PID=03eb:2404
``` 

Going to play a bit with **pyserial** to see if I can obtain the desired output.. 

Alternatively I can just skip this. I use my Arduino IDE GUI and it will verify and upload the sketch provided and the serial it gives is: /dev/ttyACM0.

**Comment by tmopencell** [comment]
Ok so if I type: 

```
for p in serial.tools.list_ports.comports():
     print (p.device)

/dev/ttyACM0
/dev/ttyAMA0
```

**Comment by tmopencell** [comment]
**FIX**

Fixed this by editing **Arduino.py**:
`sudo nano arduino.py`

Edit **line 31** to comment out `if 'ACM' in p.description`. It should now read: 
```
#if 'ACM' in p.description
```
